[[redirects]]
  from = "/en"
  to = "/en/home/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/"
  to = "/fr/"
  status = 301
  force = true

[[redirects]]
  from = "/fr/home/"
  to = "/fr/"
  status = 301
  force = true

[[redirects]]
  from = "https://africtivistes.org/*"
  to = "https://africtivistes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.africtivistes.org/*"
  to = "https://www.africtivistes.com/:splat"
  status = 301
  force = true