[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  GATSBY_CPU_COUNT = "2"

[[redirects]]
  from = "/en"
  to = "/en/home"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"]}