name: Add to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    permissions:
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - name: "🔖 Issue add"
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/AfricTivistes/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
